In [4]:
import numpy as np

In [5]:
N=8
board_state_memory={}
board = np.zeros((N,N), np.int8)

In [6]:
def create_board_string(board):
    board_string = ''
    for i in range(N):
        for j in range(N):
            board_string += str(board[i][j])
    return board_string

In [7]:
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [8]:
board_copy = board.copy()
board_copy[0,1]=1
create_board_string(board_copy)

'0100000000000000000000000000000000000000000000000000000000000000'

In [45]:
def is_board_safe(board):
    board_key = create_board_string(board)
    if board_key in board_state_memory:
        return board_state_memory[board_key]
    row_sum = np.sum(board,axis=1)
    if len(row_sum[np.where(row_sum>1)]) > 0:
        board_state_memory[board_key] = False
        return False
    col_sum = np.sum(board,axis=0)
    if len(col_sum[np.where(col_sum>1)]) > 0:
        board_state_memory[board_key] = False
        return False
    diags = [board[::-1,:].diagonal(i) for i in range(-board.shape[0]+1, board.shape[1])]
    diags.extend(board.diagonal(i) for i in range(board.shape[1]-1, -board.shape[0], -1))
    for diag in diags:
        if np.sum(diag)> 1 :
            board_state_memory[board_key] = False
            return False
    board_state_memory[board_key] = True
    return True
    

In [37]:
def place_queen(board, column):
    if column >= N:
        return True
    for row in range(N):
        board[row][column] = 1
        safe = False
        if is_board_safe(board):
            safe = place_queen(board,column+1)
        if not safe:
            board[row][column] = 0
        else:
            break
    return safe

        

In [59]:
board = np.zeros((N,N), np.int8)
placed = place_queen(board, 0)
print(placed)
print(board)

True
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]


In [ ]:
#

In [24]:
board_temp = np.array([ i*N + j for i in range(N) for j in range(N)])
board_temp = board_temp.reshape((N,N))
board_temp[::-1,:].diagonal(3)

array([59, 52, 45, 38, 31])

In [25]:
board_temp

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [30]:
board_temp.diagonal(-1)

array([ 8, 17, 26, 35, 44, 53, 62])